- project:
    check:
      jobs:
        - "thoth-coala"
        - "thoth-pytest"
    gate:
      queue: "thoth-station/core"
      jobs:
        - "thoth-coala"
        - "thoth-pytest"
    post:
      jobs:
        - trigger-build:
            vars:
              cluster: "paas.psi.redhat.com"
              namespace: "thoth-test-core"
              buildConfigName: "graph-backup-job"

    kebechet-auto-gate:
      queue: "thoth-station/core"
      jobs:
        - "thoth-coala"
        - "thoth-pytest"
